/**:
  ros__parameters:
   x_min: -6.0    #截取点云，x方向最小值
   x_max: 1.0    #截取点云，x方向最大值
   y_min: -3.5   #截取点云，y方向最小值
   y_max: 3.5    #截取点云，y方向最大值
   z_min: 0.2   #截取点云，z方向最小值
   z_max: 4.0    #截取点云，z方向最大值
   sync_diff: 0.1 #点云和图像同步允许时间差（s)
   T_lidar_camera:   #lidar to camera 外参矩阵
    [0.0186132,   0.993591,   -0.111491,    0.21662108,
    0.401126,   -0.109564,   -0.909447,    1.85447976,
    -0.915834,   -0.0277944,  -0.400595,    0.42084404,
       0.0, 0.0, 0.0, 1.0]
